/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mainpkg_JcCURL */

#ifndef _Included_mainpkg_JcCURL
#define _Included_mainpkg_JcCURL
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     mainpkg_JcCURL
	 * Method:    teste
	 * Signature: (I)V
	 */
	JNIEXPORT void JNICALL Java_mainpkg_JcCURL_teste
	(JNIEnv*, jobject, jint);

	/*
	 * Class:     mainpkg_JcCURL
	 * Method:    cURLget
	 * Signature: (Ljava/lang/String;)Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_mainpkg_JcCURL_cURLget
	(JNIEnv*, jobject, jstring);

	/*
	 * Class:     mainpkg_JcCURL
	 * Method:    cURLpost
	 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_mainpkg_JcCURL_cURLpost
	(JNIEnv*, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
